version: '2.0'
services:
  media_conduit:
    container_name: "media_repo_conduit"
    #image: "matrixconduit/matrix-conduit:latest"
    image: "conduit-local"
    restart: unless-stopped
    volumes:
      - ./conduit-db:/srv/conduit/.local/share/conduit
      - ./conduit.toml:/srv/conduit/conduit.toml
    ports:
      - "6167:6167"
    networks:
      - media_proxy
  media_nginx:
    container_name: "media_repo_nginx"
    image: "nginx:latest"
    restart: unless-stopped
    volumes:
      - ./conduit.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8008:80"
    networks:
      - media_proxy
  media_element:
    container_name: "media_repo_element"
    image: "vectorim/element-web:latest"
    restart: unless-stopped
    volumes:
      - ./element-config.json:/app/config.json
    networks:
      - media_proxy
  media_psql:
    container_name: "media_repo_psql"
    image: "postgres"
    restart: unless-stopped
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "test1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - media_proxy
networks:
  media_proxy:
