name: Main
on:
  push:
jobs:
  build:
    name: 'Go Build (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: "Install libheif"
        run: "chmod +x ./.github/workflows/build-libheif.sh && ./.github/workflows/build-libheif.sh"
      - run: './build.sh' # verify the thing compiles
  static:
    name: 'Go Static (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: "Install libheif"
        run: "chmod +x ./.github/workflows/build-libheif.sh && ./.github/workflows/build-libheif.sh"
      - name: "Prepare: compile assets"
        run: "GOBIN=$PWD/bin go install -v ./cmd/compile_assets"
      - name: "Run: compile assets"
        run: "$PWD/bin/compile_assets"
      - name: "Prepare: staticcheck"
        run: 'go install honnef.co/go/tools/cmd/staticcheck@latest'
      - run: 'go vet ./...'
      - run: 'staticcheck ./...'
  test:
    name: 'Go Test (1.20)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: "Prepare: compile assets"
        run: "GOBIN=$PWD/bin go install -v ./cmd/compile_assets"
      - name: "Run: compile assets"
        run: "$PWD/bin/compile_assets"
      - name: "Run: tests"
        run: "go test -c -v ./test && ./test.test '-test.v'" # cheat and work around working directory issues
        timeout-minutes: 30
