name: Main
on:
  push:
jobs:
  build:
    name: 'Go Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: "Install libheif"
        run: "chmod +x ./.github/workflows/build-libheif.sh && ./.github/workflows/build-libheif.sh"
      - run: './build.sh' # verify the thing compiles
  static:
    name: 'Go Static'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: "Install libheif"
        run: "chmod +x ./.github/workflows/build-libheif.sh && ./.github/workflows/build-libheif.sh"
      - name: "Prepare: compile assets"
        run: "GOBIN=$PWD/bin go install -v ./cmd/utilities/compile_assets"
      - name: "Run: compile assets"
        run: "$PWD/bin/compile_assets"
      - name: "Prepare: staticcheck"
        run: 'go install honnef.co/go/tools/cmd/staticcheck@latest'
      - run: 'go vet ./cmd/...'
      - run: 'staticcheck ./cmd/...'
  test:
    name: 'Go Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: "Prepare: compile assets"
        run: "GOBIN=$PWD/bin go install -v ./cmd/utilities/compile_assets"
      - name: "Run: compile assets"
        run: "$PWD/bin/compile_assets"
      - name: "Run: tests"
        run: "go test -c -v ./test && ./test.test '-test.v' -test.parallel 1" # cheat and work around working directory issues
        timeout-minutes: 30
